### ISSUE TITLE
augeas lens configuration fails when installing pgpool 4.1.2

### ISSUE THREAD

**Issue by zenbiking** [mwhahaha/augeas-pgpool#3]
When attempting to use this lens and the mwahaha/pgpool module to install pgpool 4.1.2 the lens fails to run because there are two configuration lines on pgpool.conf that contain non-quoted keywords. 

"check_temp_table = catalog" and "relcache_query_target = master"

I have basically no experience with augeas, but I've been able to verify that adding single quotes around the words "catalog" and "master" allow augeas to continue to parse the file and successfully write out changes. Based on what I can see in the configuration, it doesn't appear that the values for these options are supposed to be quoted.

**Comment by zenbiking** [comment]
i see that this has been addressed in the latest update. Do you have a timeline for updating the module on Puppet Forge to include recent changes?

**Comment by mwhahaha** [comment]
I'll try and get to this today

**Comment by zenbiking** [comment]
Thank you!

**Comment by mwhahaha** [comment]
I assume you were looking for a new version of the mwhahaha-pgpool stuff. So I've pushed v0.2.0 with updates and a newer version of this included. Let me know if you needed something else.
